# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://gokkulnath.github.io/dialga/"

git_url = "https://github.com/gokkulnath/dialga/tree/master/"

def custom_doc_links(name): return None
